{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedRecordDot #-}

module Slider where

import Underlying
import Type
import Engine.Collector
import Engine.Container
import Engine.Helper
import Engine.Projection
import Engine.Selector
import Engine.Type
import Engine.Underlying
import qualified Error.Function as EF
import qualified Error.Type as ET
import qualified Data.Sequence as DS
import qualified Foreign.C.Types as FCT

above_thumb::ET.Has_call_stack=>Bool->FCT.CFloat->FCT.CFloat->Arrange->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->Bool
above_thumb horizontal click_x click_y arrange x y thumb_position thumb_length radius=if horizontal then above_extension_box click_x click_y arrange thumb_position y (thumb_length/2) radius else above_extension_box click_x click_y arrange x thumb_position radius (thumb_length/2)

calculate_thumb_length::ET.Has_call_stack=>FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat
calculate_thumb_length content_size viewport_size min_thumb_length track_geometric_length=if content_size<=0 then track_geometric_length else max min_thumb_length (track_geometric_length*viewport_size/content_size)

calculate_thumb_position::ET.Has_call_stack=>Bool->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat
calculate_thumb_position horizontal content_size viewport_size offset track_start_position track_end_position thumb_length=if content_size<=viewport_size then track_start_position+(track_end_position-track_start_position)/2 else if horizontal then track_start_position+(track_end_position-track_start_position-thumb_length)*offset/(content_size-viewport_size)+thumb_length/2 else track_start_position+(track_end_position-track_start_position+thumb_length)*offset/(content_size-viewport_size)-thumb_length/2

create_slider_request::ET.Has_call_stack=>Custom_extension a=>(Event a->Engine a->Maybe Int)->Extension_visual_request a->Widget_request a
create_slider_request next slider_request=case slider_request of
    Slider_request {}->Visual_trigger_request {next=next,visual_trigger=slider_visual_trigger,visual_request=Custom_visual_request {custom=slider_request}}
    _->EF.empty_error

create_slider_visual::ET.Has_call_stack=>Custom_extension a=>Extension_visual_request a->Engine a->IO (Engine a,Extension_visual a)
create_slider_visual slider_request engine=case slider_request of
    Slider_request {window_id,leaf_id,selector,getter,setter,arrange,x,y,slider_width,slider_height,inner_thickness,outer_thickness,min_thumb_length,step_size,horizontal,color,outer_color,triangle_color,triangle_hovered_color,triangle_pressed_color,thumb_color,thumb_hovered_color,thumb_pressed_color}->let half_width=slider_width/2 in let half_height=slider_height/2 in let radius=if horizontal then half_height-2*inner_thickness else half_width-2*inner_thickness in let first_triangle_center_x=if horizontal then x-half_width+inner_thickness+radius else x in let first_triangle_center_y=if horizontal then y else y+half_height-inner_thickness-radius in let second_triangle_center_x=if horizontal then x+half_width-inner_thickness-radius else x in let second_triangle_center_y=if horizontal then y else y-half_height+inner_thickness+radius in let track_start_position=if horizontal then first_triangle_center_x+radius+inner_thickness else first_triangle_center_y-radius-inner_thickness in let track_end_position=if horizontal then second_triangle_center_x-radius-inner_thickness else second_triangle_center_y+radius+inner_thickness in let (content_size,viewport_size,current_offset)=getter (selector_action (\_ this_widget _->this_widget) selector (lookup_projection_widget (Object_path {leaf_id=leaf_id}) engine) (lookup_projection_widget (Object_path {leaf_id=leaf_id}) engine)) in let track_geometric_length=abs (track_end_position-track_start_position) in let thumb_length=calculate_thumb_length content_size viewport_size min_thumb_length track_geometric_length in let thumb_position=calculate_thumb_position horizontal content_size viewport_size current_offset track_start_position track_end_position thumb_length in return (engine,Slider {window_id=window_id,leaf_id=leaf_id,selector=selector,getter=getter,setter=setter,arrange=arrange,x=x,y=y,half_width=half_width,half_height=half_height,inner_thickness=inner_thickness,outer_thickness=outer_thickness,min_thumb_length=min_thumb_length,step_size=step_size,thumb_length=thumb_length,thumb_position=thumb_position,drag_position=0,drag_offset=0,cached_offset=current_offset,horizontal=horizontal,dirty=True,thumb_state=Slider_normal,first_triangle_state=Slider_normal,second_triangle_state=Slider_normal,color=color,outer_color=outer_color,triangle_color=triangle_color,triangle_hovered_color=triangle_hovered_color,triangle_pressed_color=triangle_pressed_color,thumb_color=thumb_color,thumb_hovered_color=thumb_hovered_color,thumb_pressed_color=thumb_pressed_color})
    _->EF.empty_error

get_slider_color::ET.Has_call_stack=>Slider_state->Color->Color->Color->Color
get_slider_color state normal hovered pressed=case state of
    Slider_normal->normal
    Slider_hovered->hovered
    Slider_pressed->pressed

update_slider_state::ET.Has_call_stack=>Bool->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->FCT.CFloat->Slider_state->Slider_state->Slider_state->Extension_visual a->Extension_visual a
update_slider_state dirty thumb_length thumb_position drag_position drag_offset cached_offset thumb_state first_triangle_state second_triangle_state slider=case slider of
    Slider {window_id,leaf_id,selector,getter,setter,arrange,x,y,half_width,half_height,inner_thickness,outer_thickness,min_thumb_length,step_size,horizontal,color,outer_color,triangle_color,triangle_hovered_color,triangle_pressed_color,thumb_color,thumb_hovered_color,thumb_pressed_color}->Slider {window_id=window_id,leaf_id=leaf_id,selector=selector,getter=getter,setter=setter,arrange=arrange,x=x,y=y,half_width=half_width,half_height=half_height,inner_thickness=inner_thickness,outer_thickness=outer_thickness,min_thumb_length=min_thumb_length,step_size=step_size,thumb_length=thumb_length,thumb_position=thumb_position,drag_position=drag_position,drag_offset=drag_offset,cached_offset=cached_offset,horizontal=horizontal,dirty=dirty,thumb_state=thumb_state,first_triangle_state=first_triangle_state,second_triangle_state=second_triangle_state,color=color,outer_color=outer_color,triangle_color=triangle_color,triangle_hovered_color=triangle_hovered_color,triangle_pressed_color=triangle_pressed_color,thumb_color=thumb_color,thumb_hovered_color=thumb_hovered_color,thumb_pressed_color=thumb_pressed_color}
    _->EF.empty_error

slider_visual_trigger::ET.Has_call_stack=>Custom_extension a=>Event a->Engine a->Visual a->(Visual a,Engine a->Engine a)
slider_visual_trigger event engine visual=case event of
    At {window_id=this_window_id,action}->case visual of
        Custom_visual {custom}->case custom of
            Slider {window_id,leaf_id,selector,getter,setter,arrange,x,y,half_width,half_height,inner_thickness,min_thumb_length,step_size,thumb_length,thumb_position,drag_position,drag_offset,cached_offset,horizontal,thumb_state,first_triangle_state,second_triangle_state}->if this_window_id==window_id
                then let radius=if horizontal then half_height-2*inner_thickness else half_width-2*inner_thickness in let first_triangle_center_x=if horizontal then x-half_width+inner_thickness+radius else x in let first_triangle_center_y=if horizontal then y else y+half_height-inner_thickness-radius in let second_triangle_center_x=if horizontal then x+half_width-inner_thickness-radius else x in let second_triangle_center_y=if horizontal then y else y-half_height+inner_thickness+radius in let track_start_position=if horizontal then first_triangle_center_x+radius+inner_thickness else first_triangle_center_y-radius-inner_thickness in let track_end_position=if horizontal then second_triangle_center_x-radius-inner_thickness else second_triangle_center_y+radius+inner_thickness in let (content_size,viewport_size,current_offset)=getter (selector_action (\_ this_widget _->this_widget) selector (lookup_projection_widget (Object_path {leaf_id=leaf_id}) engine) (lookup_projection_widget (Object_path {leaf_id=leaf_id}) engine)) in let track_geometric_length=abs (track_end_position-track_start_position) in let new_thumb_length=calculate_thumb_length content_size viewport_size min_thumb_length track_geometric_length in let new_thumb_position=calculate_thumb_position horizontal content_size viewport_size current_offset track_start_position track_end_position new_thumb_length in case action of
                    Click {press,mouse_button,x=click_x,y=click_y}->case mouse_button of
                        Mouse_button_left->case press of
                            Press_down->let (local_x,local_y)=get_local_coordinate click_x click_y arrange in let hit_first_triangle_flag=above_triangle local_x local_y first_triangle_center_x first_triangle_center_y radius in let hit_second_triangle_flag=above_triangle local_x local_y second_triangle_center_x second_triangle_center_y radius in let hit_thumb_flag=if horizontal then above_box local_x local_y thumb_position y (thumb_length/2) radius else above_box local_x local_y x thumb_position radius (thumb_length/2) in if hit_first_triangle_flag then let new_offset=max 0 (cached_offset-step_size) in let new_slider=update_slider_state True new_thumb_length (calculate_thumb_position horizontal content_size viewport_size new_offset track_start_position track_end_position new_thumb_length) drag_position drag_offset new_offset thumb_state Slider_pressed second_triangle_state custom in if cached_offset/=new_offset
                                then case setter cached_offset new_offset of
                                    Just update_function->(Custom_visual {custom=new_slider},\this_engine->this_engine {leaf=int_map_update leaf_id (update_projection_object (selector_update (const update_function) selector)) this_engine.leaf})
                                    Nothing->(Custom_visual {custom=new_slider},id)
                                else (Custom_visual {custom=new_slider},id) else if hit_second_triangle_flag then let new_offset=min (max 0 (content_size-viewport_size)) (cached_offset+step_size) in let new_slider=update_slider_state True new_thumb_length (calculate_thumb_position horizontal content_size viewport_size new_offset track_start_position track_end_position new_thumb_length) drag_position drag_offset new_offset thumb_state first_triangle_state Slider_pressed custom in if cached_offset/=new_offset
                                    then case setter cached_offset new_offset of
                                        Just update_function->(Custom_visual {custom=new_slider},\this_engine->this_engine {leaf=int_map_update leaf_id (update_projection_object (selector_update (const update_function) selector)) this_engine.leaf})
                                        Nothing->(Custom_visual {custom=new_slider},id)
                                    else (Custom_visual {custom=new_slider},id) else if hit_thumb_flag then (Custom_visual {custom=update_slider_state True thumb_length thumb_position (if horizontal then local_x else local_y) cached_offset cached_offset Slider_pressed first_triangle_state second_triangle_state custom},id) else let track_half_length=abs (track_end_position-track_start_position)/2 in let track_center=track_start_position+(track_end_position-track_start_position)/2 in let track_jump_half_width=if horizontal then track_half_length else half_width in let track_jump_half_height=if horizontal then half_height else track_half_length in if above_box local_x local_y (if horizontal then track_center else x) (if horizontal then y else track_center) track_jump_half_width track_jump_half_height then let start_center=track_start_position+(if horizontal then new_thumb_length/2 else -new_thumb_length/2) in let end_center=track_end_position+(if horizontal then -new_thumb_length/2 else new_thumb_length/2) in let travel_distance=if horizontal then end_center-start_center else start_center-end_center in let click_pos=if horizontal then local_x else local_y in let ratio=max 0 (min 1 (if travel_distance==0 then 0 else (if horizontal then click_pos-start_center else start_center-click_pos)/travel_distance)) in let new_offset=ratio*max 0 (content_size-viewport_size) in let new_thumb_position_after_jump=calculate_thumb_position horizontal content_size viewport_size new_offset track_start_position track_end_position new_thumb_length in let hit_thumb_after_jump=if horizontal then above_box local_x local_y new_thumb_position_after_jump y (new_thumb_length/2) radius else above_box local_x local_y x new_thumb_position_after_jump radius (new_thumb_length/2) in let new_thumb_state=if hit_thumb_after_jump then Slider_hovered else Slider_normal in let new_slider=update_slider_state True new_thumb_length new_thumb_position_after_jump drag_position drag_offset new_offset new_thumb_state first_triangle_state second_triangle_state custom in let cursor_action=if thumb_state==Slider_normal&&hit_thumb_after_jump then \this_engine->this_engine {request=this_engine.request DS.|> Set_system_cursor {system_cursor=System_cursor_pointer}} else id in if cached_offset/=new_offset
                                        then case setter cached_offset new_offset of
                                            Just update_function->(Custom_visual {custom=new_slider},\this_engine->cursor_action (this_engine {leaf=int_map_update leaf_id (update_projection_object (selector_update (const update_function) selector)) this_engine.leaf}))
                                            Nothing->(Custom_visual {custom=new_slider},cursor_action)
                                        else (Custom_visual {custom=new_slider},cursor_action) else (visual,id)
                            Press_up->let (local_x,local_y)=get_local_coordinate click_x click_y arrange in let hit_first_triangle_flag=above_triangle local_x local_y first_triangle_center_x first_triangle_center_y radius in let hit_second_triangle_flag=above_triangle local_x local_y second_triangle_center_x second_triangle_center_y radius in let hit_thumb_flag=if horizontal then above_box local_x local_y thumb_position y (thumb_length/2) radius else above_box local_x local_y x thumb_position radius (thumb_length/2) in let was_hovered=Slider_normal/=first_triangle_state||Slider_normal/=second_triangle_state||Slider_normal/=thumb_state in let is_hovered=hit_first_triangle_flag||hit_second_triangle_flag||hit_thumb_flag in let cursor_action=if was_hovered/=is_hovered then if is_hovered then \this_engine->this_engine {request=this_engine.request DS.|> Set_system_cursor {system_cursor=System_cursor_pointer}} else \this_engine->this_engine {request=this_engine.request DS.|> Set_system_cursor {system_cursor=System_cursor_default}} else id in (Custom_visual {custom=update_slider_state True thumb_length thumb_position drag_position drag_offset cached_offset (if hit_thumb_flag then Slider_hovered else Slider_normal) (if hit_first_triangle_flag then Slider_hovered else Slider_normal) (if hit_second_triangle_flag then Slider_hovered else Slider_normal) custom},cursor_action)
                        _->(visual,id)
                    Move {x=move_x,y=move_y}->let (local_x,local_y)=get_local_coordinate move_x move_y arrange in if thumb_state==Slider_pressed
                        then let scrollable=content_size-viewport_size in let track_movable_length=max 0 (track_geometric_length-new_thumb_length) in let move_pos=if horizontal then local_x else local_y in let final_offset=max 0 (min scrollable (drag_offset+(if track_movable_length==0 then 0 else (if horizontal then move_pos-drag_position else drag_position-move_pos)/track_movable_length*scrollable))) in let new_slider=update_slider_state True new_thumb_length (calculate_thumb_position horizontal content_size viewport_size final_offset track_start_position track_end_position new_thumb_length) drag_position drag_offset final_offset thumb_state first_triangle_state second_triangle_state custom in case setter cached_offset final_offset of
                            Just update_function->(Custom_visual {custom=new_slider},\this_engine->this_engine {leaf=int_map_update leaf_id (update_projection_object (selector_update (const update_function) selector)) this_engine.leaf})
                            Nothing->(Custom_visual {custom=new_slider},id)
                        else let hit_first_triangle_flag=above_triangle local_x local_y first_triangle_center_x first_triangle_center_y radius in let hit_second_triangle_flag=above_triangle local_x local_y second_triangle_center_x second_triangle_center_y radius in let hit_thumb_flag=if horizontal then above_box local_x local_y new_thumb_position y (new_thumb_length/2) radius else above_box local_x local_y x new_thumb_position radius (new_thumb_length/2) in let new_first_triangle_state=if first_triangle_state==Slider_pressed then Slider_pressed else if hit_first_triangle_flag then Slider_hovered else Slider_normal in let new_second_triangle_state=if second_triangle_state==Slider_pressed then Slider_pressed else if hit_second_triangle_flag then Slider_hovered else Slider_normal in let new_thumb_state=if thumb_state==Slider_pressed then Slider_pressed else if hit_thumb_flag then Slider_hovered else Slider_normal in let state_changed=first_triangle_state/=new_first_triangle_state||second_triangle_state/=new_second_triangle_state||thumb_state/=new_thumb_state||current_offset/=cached_offset||new_thumb_length/=thumb_length||new_thumb_position/=thumb_position in let was_hovered=Slider_normal/=first_triangle_state||Slider_normal/=second_triangle_state||Slider_normal/=thumb_state in let is_hovered=hit_first_triangle_flag||hit_second_triangle_flag||hit_thumb_flag in let cursor_action=if was_hovered/=is_hovered then if is_hovered then \this_engine->this_engine {request=this_engine.request DS.|> Set_system_cursor {system_cursor=System_cursor_pointer}} else \this_engine->this_engine {request=this_engine.request DS.|> Set_system_cursor {system_cursor=System_cursor_default}} else id in if state_changed then (Custom_visual {custom=update_slider_state True new_thumb_length new_thumb_position drag_position drag_offset current_offset new_thumb_state new_first_triangle_state new_second_triangle_state custom},cursor_action) else (visual,id)
                    _->if current_offset/=cached_offset||new_thumb_position/=thumb_position||new_thumb_length/=thumb_length then (Custom_visual {custom=update_slider_state True new_thumb_length new_thumb_position drag_position drag_offset current_offset thumb_state first_triangle_state second_triangle_state custom},id) else (visual,id)
                else (visual,id)
            _->(visual,id)
        _->(visual,id)
    _->(visual,id)

collect_slider_visual::ET.Has_call_stack=>Custom_extension a=>(Arrange->Arrange)->FCT.CFloat->FCT.CFloat->Maybe (Border FCT.CFloat)->Extension_visual a->DS.Seq (Submit a)
collect_slider_visual transform u v maybe_border slider=case slider of
    Slider {arrange,x,y,half_width,half_height,inner_thickness,outer_thickness,thumb_length,thumb_position,horizontal,thumb_state,first_triangle_state,second_triangle_state,color,outer_color,triangle_color,triangle_hovered_color,triangle_pressed_color,thumb_color,thumb_hovered_color,thumb_pressed_color}->case transform arrange of
        Arrange {point=new_point,matrix=new_matrix,color=new_color}->case arrange of
            Arrange {matrix=local_matrix}->let radius=if horizontal then half_height-2*inner_thickness else half_width-2*inner_thickness in let center_x=new_point.x+x in let center_y=new_point.y+y in let combined_matrix=multiply_matrix new_matrix local_matrix in DS.fromList [create_submit_rectangle Submit_default maybe_border (Arrange {point=Point {x=center_x,y=center_y},matrix=combined_matrix,color=multiply_color new_color outer_color}) (half_width+outer_thickness) (half_height+outer_thickness) u v u v,create_submit_rectangle Submit_default maybe_border (Arrange {point=Point {x=center_x,y=center_y},matrix=combined_matrix,color=multiply_color new_color color}) half_width half_height u v u v,create_submit_triangle Submit_default maybe_border (Arrange {point=Point {x=if horizontal then center_x-half_width+inner_thickness+radius else center_x,y=if horizontal then center_y else center_y+half_height-inner_thickness-radius},matrix=combined_matrix,color=multiply_color new_color (get_slider_color first_triangle_state triangle_color triangle_hovered_color triangle_pressed_color)}) (Point {x=if horizontal then negate radius else 0,y=if horizontal then 0 else radius}) (Point {x=if horizontal then radius else negate radius,y=if horizontal then radius else negate radius}) (Point {x=radius,y=negate radius}) u v,create_submit_triangle Submit_default maybe_border (Arrange {point=Point {x=if horizontal then center_x+half_width-inner_thickness-radius else center_x,y=if horizontal then center_y else center_y-half_height+inner_thickness+radius},matrix=combined_matrix,color=multiply_color new_color (get_slider_color second_triangle_state triangle_color triangle_hovered_color triangle_pressed_color)}) (Point {x=if horizontal then radius else 0,y=if horizontal then 0 else negate radius}) (Point {x=negate radius,y=radius}) (Point {x=if horizontal then negate radius else radius,y=if horizontal then negate radius else radius}) u v,create_submit_rectangle Submit_default maybe_border (Arrange {point=Point {x=if horizontal then new_point.x+thumb_position else center_x,y=if horizontal then center_y else new_point.y+thumb_position},matrix=combined_matrix,color=multiply_color new_color (get_slider_color thumb_state thumb_color thumb_hovered_color thumb_pressed_color)}) (if horizontal then thumb_length/2 else radius) (if horizontal then radius else thumb_length/2) u v u v]
    _->EF.empty_error

{-# INLINE above_thumb #-}
{-# INLINE calculate_thumb_length #-}
{-# INLINE calculate_thumb_position #-}
{-# INLINE create_slider_request #-}
{-# INLINE create_slider_visual #-}
{-# INLINE get_slider_color #-}
{-# INLINE update_slider_state #-}
{-# INLINE slider_visual_trigger #-}
{-# INLINE collect_slider_visual #-}