cabal-version:      3.0
name:               Hsue-Extension
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Qerfcxz
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Button
        Instance
        Page
        Slider
        Type
        Underlying
    build-depends:
        base ^>=4.20.2.0,
        bytestring ==0.12.2.0,
        containers ==0.8,
        hashable ==1.5.1.0,
        text ==2.1.4,
        transformers ==0.6.3.0,
        unordered-containers ==0.2.21,
        vector ==0.13.2.0,
        Hsue,
    hs-source-dirs:   src
    default-language: Haskell2010

executable Hsue
    import:           warnings
    main-is:          Main.hs
    ghc-options:
        -threaded
        -with-rtsopts=-N
    build-depends:
        base ^>=4.20.2.0,
        bytestring ==0.12.2.0,
        containers ==0.8,
        hashable ==1.5.1.0,
        text ==2.1.4,
        transformers ==0.6.3.0,
        unordered-containers ==0.2.21,
        vector ==0.13.2.0,
        Hsue,
        Hsue-Extension
    hs-source-dirs:   app
    default-language: Haskell2010